### ISSUE TITLE
2022.6 breaking changes

### ISSUE THREAD

**Issue by froggy974** [thehookup/Shelly-RGBW2#5]
https://www.home-assistant.io/blog/2022/06/01/release-20226/

the 2022.6 release seems to add some breaking changes on mqtt an template ( white_value)

does someone know how to update the config to make it compatible with the 2022.6 ?

**Comment by khicks** [comment]
This is definitely now broken in 2022.9. They removed the `white_value_template` option, so this config breaks the whole Mosquitto broker service.

**Comment by slatevt** [comment]
So.... how do we fix this?  Anyone have any clue?

    white_value_template: '{{ value_json.white }}'     changes to.... ??

**Comment by khicks** [comment]
No known fix yet that I'm aware of. You can switch to the Shelly integration (with CoIoT unicast for best results), or [someone reported that Node-RED also works](https://community.home-assistant.io/t/configure-shelly-rgbw2-in-newest-home-assistant/256771/24).

If all you care about is RGB with no white, you could try removing that field, but that's a non-starter for many.

**Comment by Dilergore** [comment]
Hi,

I created a PR to update this document with a working setup for the RGB+W mode. This is working for me properly, without any issues (based on the log and experience). Please get back to me if you face any issue.
